### PR TITLE
fix(getSavedConfig): catch window.localStorage error

### LINKED ISSUE #124: SecurityError: when cookies are deactivated in browser
an uncatched error is thrown when the user deactivates cookies in the browser, resulting in a crash of the whole angular app. There was the same issue with angular-translate [#629](https://github.com/angular-translate/angular-translate/issues/629). The getSavedConfig() is throwing this error first. A try/catch block would fix it, but I would personally prefer a fallback to storing the data just in a JavaScript object. What do you think about that?

The line throwing this error is actually this one:

            if $window.localStorage

### PR DESCRIPTION
**Pull request by nbrustein**
Fixes #124

### CODE REVIEW

File: dist/ng-token-auth.js [hunk 1]
```diff
@@ -583,10 +583,16 @@ angular.module('ng-token-auth', ['ipCookie']).provider('$auth', function() {
...
-              var c, key;
+              var c, error, hasLocalStorage, key;
               c = void 0;
               key = 'currentConfigName';
-              if ($window.localStorage) {
+              hasLocalStorage = false;
+              try {
+                hasLocalStorage = !!$window.localStorage;
+              } catch (_error) {
+                error = _error;
```
Comment (wedneyyuri) [inline dist/ng-token-auth.js]: Unused variable?

My suggestion is throw an error, `console.warn` also would be helpful.

Comment (nbrustein) [inline dist/ng-token-auth.js]: 1. Which unused variable do you mean?  If you mean the 'error', it seemed like coffeescript required that.  I'm no good at coffeescript, so I my have done it wrong.
1. I def don't want to throw an error, since the whole point of this PR is to suppress the error.
1. I don't think a console.warn is necessary.  This library is supposed to support situations with no local storage, so it does not really require a warning, IMO.

**Comment by booleanbetrayal** [comment]
Privacy mode, etc is a completely valid use case for a browser to be running in, so I don't think it should warn or anything. Just fall back accordingly. lgtm!
